name = "flong-dev-api"
main = "src/api-worker.js"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "."

# Routes for enhanced API functionality
routes = [
  { pattern = "flong.dev/api/*", zone_name = "flong.dev" },
  { pattern = "flong.dev/health", zone_name = "flong.dev" },
  { pattern = "flong.dev/analytics", zone_name = "flong.dev" }
]

# Environment variables
[vars]
FROM_EMAIL = "noreply@flong.dev"
TO_EMAIL = "hello@flong.dev"
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
RATE_LIMIT_ENABLED = true

# KV namespace for rate limiting and analytics
[[kv_namespaces]]
binding = "ANALYTICS"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# Analytics and monitoring
[analytics_engine_datasets]
binding = "ANALYTICS_ENGINE"

[observability.logs]
enabled = true

# Build configuration
[build]
command = "echo 'Enhanced API worker ready'"

# Miniflare for local development
[miniflare]
kv_persist = true
cache_persist = true