# Cloudflare Workers configuration
name = "flong-dev-api"
main = "src/api-worker.js"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# Routes for enhanced API functionality
routes = [
  { pattern = "flong.dev/api/*", zone_name = "flong.dev" },
  { pattern = "flong.dev/health", zone_name = "flong.dev" },
  { pattern = "flong.dev/analytics", zone_name = "flong.dev" }
]

# Environment variables
[vars]
FROM_EMAIL = "noreply@flong.dev"
TO_EMAIL = "hello@flong.dev"
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
RATE_LIMIT_ENABLED = true

[observability.logs]
enabled = true