# Cloudflare Workers Configuration for flong.dev API
name = "flong-dev-contact-form"
main = "src/api-worker.js"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# Routes - API endpoints on the domain
routes = [
  { pattern = "flong.dev/api/*", zone_name = "flong.dev" },
  { pattern = "flong.dev/health", zone_name = "flong.dev" },
  { pattern = "flong.dev/analytics", zone_name = "flong.dev" }
]

# Environment variables
[vars]
FROM_EMAIL = "noreply@flong.dev"
TO_EMAIL = "hello@flong.dev"
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
RATE_LIMIT_ENABLED = true



# Observability
[observability.logs]
enabled = true

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "7ec949f8903a41a08f7a8c010c1fe2ff"
preview_id = "1dafccbdac3e4d039c11146782290f3b"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "993d2e06a23949c9b087102d7babdfba"
preview_id = "d771c4c937264edaa81c65ea60adedaf"

[[kv_namespaces]]
binding = "CONTACTS"
id = "5529065343fb411b9f3c9e5f8028520d"
preview_id = "08df2d6a214145caa331366fb07d2240"
